import assert from 'node:assert/strict';
import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {frameDocument} from '../src/lib/runtime';
import {featuredAnswerIds} from '../src/lib/answer-order';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:5173',dir='artifacts/reviews/free-exploration';await mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true});const evidence:any={url:base,checkedAt:new Date().toISOString(),firstScreens:[],mechanisms:[]};
const actions:Record<string,[string,string,string?,string?]>={
 'dlss-pair-1':['#position','range','25','#mask'], 'population-crowd':['#working','fill','10','#crowd'],'cash-river':['#income','fill','100000','#river'],'rent-calendar':['#calendar button','click',undefined,'#calendar'],'exam-score':['#mean','click',undefined,'svg'],'door-encounter':['#advance','click',undefined,'svg'],'project-shelf':['#add','click',undefined,'#board'],'birthday-room':['#sample','click',undefined,'#room'],'network-tracks':['#count','fill','12','svg'],'focus-window':['#street','click',undefined,'.scene'],'layer-route':['#query','range','20','svg'],'density-scale':['#volume','fill','10','svg'],'light-post':['#send','click',undefined,'svg'],'cash-reserve':['#income','fill','0','svg'],'protein-plate':['#egg','fill','5','#plate'],'umbrella-race':['[data-phone="busy"]','click',undefined,'#busy .screen'],'desk-archive':['#y2021','click',undefined,'#desk']};
try{
 for(const width of [740,360]){const height=width===360?800:1000,context=await browser.newContext({viewport:{width,height},hasTouch:width===360}),page=await context.newPage();await page.goto(base);await page.locator('.answer-card').first().frameLocator('iframe').locator('#wipe').waitFor({timeout:30000});const order=await page.locator('.answer-card').evaluateAll(els=>els.map(e=>e.id));assert.deepEqual(order.slice(0,7),featuredAnswerIds);assert.equal(order.length,17);const frame=page.locator('.answer-card').first().frameLocator('iframe'),box=await frame.locator('#compare').boundingBox();assert.ok(box&&box.y+box.height<=height,'whole first picture in initial viewport');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const line=await frame.locator('#line').boundingBox();assert.ok(line&&line.y<height);await page.screenshot({path:dir+'/first-'+width+'.png'});const f=page.locator('.answer-card').first();assert.equal(await f.locator('[data-block="dlss-pair-1"]').count(),1);await frame.locator('#position').press('ArrowRight');await f.getByRole('button',{name:'完整原文',exact:true}).click();await f.getByRole('button',{name:'互动阅读',exact:true}).click();assert.equal(await frame.locator('#status').innerText(),'A 区域 51%；B 区域 49%','mode toggle preserves instance');evidence.firstScreens.push({width,height,picture:box,order,modePreservesState:true});await context.close();
 }
 for(const file of (await readdir('src/data/generated')).filter(x=>x.endsWith('.json'))){const item=JSON.parse(await readFile('src/data/generated/'+file,'utf8')),a=item.artifact,b=a.blocks.find((b:any)=>b.id===a.presentation?.leadBlockId);assert.ok(b,'core metadata '+file);const action=actions[b.id];assert.ok(action,'defined mechanism '+b.id);
 for(const width of [740,360]){const page=await browser.newPage({viewport:{width,height:1000},hasTouch:width===360});await page.route('http://mechanism.test/',r=>r.fulfill({contentType:'text/html',body:'<iframe id="demo" sandbox="allow-scripts" style="width:100%;border:0;height:2000px"></iframe><script>addEventListener("message",e=>{if(e.data.type==="resize")document.getElementById("demo").style.height=Math.min(6000,e.data.value)+"px"})</script>'}));await page.goto('http://mechanism.test/');await page.locator('#demo').evaluate((el,doc)=>(el as HTMLIFrameElement).srcdoc=doc,frameDocument(b,b.id,'http://mechanism.test',item.assets||[]));const f=page.frameLocator('#demo'),[selector,kind,value,graphic='svg']=action;const target=f.locator(selector).first();await target.waitFor();const visual=f.locator(graphic).first();const before=await visual.evaluate(e=>e.outerHTML);await page.screenshot({path:dir+'/'+a.answerId+'-'+width+'-before.png'});if(kind==='click'){if(width===360)await target.tap();else await target.click()}else if(kind==='fill')await target.fill(value!);else await target.evaluate((e,v)=>{(e as HTMLInputElement).value=v!;e.dispatchEvent(new Event('input',{bubbles:true}))},value);const after=await visual.evaluate(e=>e.outerHTML);assert.notEqual(after,before,'actual rendered mechanism must change '+file+' '+width);assert.ok(await f.locator('body').evaluate(e=>e.scrollWidth<=e.clientWidth+2),'frame overflow '+file);await page.screenshot({path:dir+'/'+a.answerId+'-'+width+'-after.png'});evidence.mechanisms.push({id:a.answerId,block:b.id,width,action:selector,graphic,changed:true});await page.close()}}
 await writeFile(dir+'/evidence.json',JSON.stringify(evidence,null,2));console.log('Initial viewport, fixed order, one live core, preserved mode state and 34 core visual changes passed.');
}finally{await browser.close()}
