import{chromium}from'playwright';import assert from'node:assert/strict';import{readFile,mkdir,writeFile}from'node:fs/promises';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:5173',browser=await chromium.launch();const context=await browser.newContext({viewport:{width:740,height:1000}}),p=await context.newPage();
try{
 const item=JSON.parse(await readFile('src/data/generated/studio-3d0c8ad5-ea44-4f61-9530-f086b7135a6f.json','utf8')),saved={...item,votes:0,accent:'#123',tag:'私有旧副本',workspace:{revision:7,idea:'私有想法应被保留',updatedAt:new Date().toISOString(),selectedParagraphIds:[]},artifact:{...item.artifact,explanation:'仅个人旧版可见的保存内容'}};
 await p.route('**/api/config',r=>r.fulfill({json:{authRequired:true,loginConfigured:true,user:{id:'test-account',name:'测试身份',avatar:''},generationEnabled:false,workspaceEnabled:true,tiers:[],timeoutMs:120000}}));
 await p.route('**/api/workspace',r=>r.fulfill({json:[saved]}));await p.route('**/api/feed?*',r=>r.fulfill({json:{items:[],next:null}}));await p.goto(base);await p.getByText('已连接后台',{exact:true}).waitFor();await p.getByRole('textbox',{name:'搜索本页回答'}).fill('哪一件事让你意识到打工没出路');const card=p.locator('.answer-card');assert.equal(await card.locator('.process-note p').innerText(),item.artifact.explanation);await p.getByRole('tab',{name:'我的作品',exact:true}).click();assert.equal(await card.locator('.process-note p').innerText(),saved.artifact.explanation);await p.getByRole('tab',{name:'全部回答 17',exact:true}).click();assert.equal(await card.locator('.process-note p').innerText(),item.artifact.explanation);
 const cash=card.locator('[data-block="cash-river"]').frameLocator('iframe');await cash.locator('#income').fill('100000');await cash.locator('#override').fill('50000');await cash.locator('#override').press('Tab');const before=await cash.locator('#pv').innerText();const wageArea=card.locator('[data-block="wage-stamps"]');await wageArea.scrollIntoViewIfNeeded();const wage=wageArea.frameLocator('iframe');await wage.locator('#hours').fill('8');assert.equal(await cash.locator('#income').inputValue(),'100000');assert.equal(await cash.locator('#pv').innerText(),before,'late wage init and changes must not overwrite manual income');await cash.locator('#sync').click();assert.equal(await cash.locator('#income').inputValue(),'43800');assert.equal(await cash.locator('#override').inputValue(),'50000','single year survives wage linking');await cash.locator('#undo-year').click();assert.equal(await cash.locator('#override').inputValue(),'43800');await cash.locator('#reset').click();assert.equal(await cash.locator('#pv').innerText(),'1,136,086.59 元');
 await mkdir('artifacts/reviews/free-exploration',{recursive:true});await writeFile('artifacts/reviews/free-exploration/public-workspace.json',JSON.stringify({checkedAt:new Date().toISOString(),identity:'explicit mocked test account, not a real OAuth check',privateOldCopyPreserved:true,publicCurrentUnaffected:true,lateSharedState:true,manualYearPreserved:true},null,2));console.log('Public current version, private old copy, delayed shared state and individual-year override checks passed.');
}finally{await browser.close()}
