import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile,readdir} from 'node:fs/promises';
const base=process.env.TEST_BASE_URL;if(!base)throw Error('Provide TEST_BASE_URL for explicit production acceptance');
const dir='artifacts/reviews/release-production';await mkdir(dir,{recursive:true});const browser=await chromium.launch({headless:true}),evidence:any={url:base,checkedAt:new Date().toISOString(),views:[],media:[]};
try{
 for(const width of [740,360]){const context=await browser.newContext({viewport:{width,height:width===360?800:1000},hasTouch:width===360});const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByRole('status').filter({hasText:'游客阅读'}).waitFor();assert.equal(await page.locator('.answer-card').count(),17);
 const meta=await page.locator('.answer-card .source-meta').allTextContents();assert.equal(meta.findIndex(s=>s.includes('原创示例')),7);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.getByRole('tab',{name:'讨论发现',exact:true}).click();await page.getByText('尚未同步讨论。精选回答仍可直接阅读。',{exact:true}).waitFor();
 await page.getByRole('tab',{name:'全部回答 17',exact:true}).click();await page.getByRole('textbox',{name:'搜索本页回答'}).fill('DLSS');const article=page.locator('.answer-card');const frame=page.frameLocator('iframe').first();await frame.getByRole('button',{name:'恢复中点',exact:true}).waitFor({timeout:25000});await frame.locator('#before').click();assert.equal(await frame.locator('#status').innerText(),'A 区域 100%；B 区域 0%');await frame.locator('#after-only').click();assert.equal(await frame.locator('#status').innerText(),'A 区域 0%；B 区域 100%');if(width===360)await frame.locator('#both').tap();else await frame.locator('#both').click();await frame.locator('#position').press('ArrowRight');assert.equal(await frame.locator('#status').innerText(),'A 区域 51%；B 区域 49%');await frame.locator('#both').click();await page.screenshot({path:dir+'/reading-'+width+'.png',fullPage:false});
 await article.getByRole('button',{name:'完整原文',exact:true}).click();await article.locator('iframe').first().waitFor({state:'hidden'});assert.equal(await article.locator('iframe:visible').count(),0);assert.ok(await article.locator('img').count()>10);assert.equal(errors.length,0);evidence.views.push({width,errors,realSourcesFirst:7,checks:['guest read','discussion empty state','saved original images','image comparison reset','source-only fallback','no horizontal overflow']});await context.close()}
 const config=await(await fetch(base+'/api/config')).json();assert.equal(config.authRequired,true);assert.equal(config.user,null);assert.equal(config.generationEnabled,false);evidence.loginConfigured=config.loginConfigured;
 for(const [path,status]of [['/studio/',404],['/tests/flow.html',404],['/api/workspace',401],['/api/admin/jobs/claim',401]] as const){const r:Response=await fetch(base+path,{method:path.includes('claim')?'POST':'GET'});assert.equal(r.status,status)}
 for(const name of (await readdir('src/data/generated')).filter(f=>f.endsWith('.json'))){const local=JSON.parse(await readFile('src/data/generated/'+name,'utf8'));const response:Response=await fetch(base+'/api/media/'+local.source.id);assert.equal(response.status,200);const assets=await response.json();assert.deepEqual(assets.map((a:any)=>a.sha256),(local.assets||[]).map((a:any)=>a.sha256));evidence.media.push({id:local.source.id,count:assets.length,sha256:assets.map((a:any)=>a.sha256)})}
 await writeFile(dir+'/evidence.json',JSON.stringify(evidence,null,2));console.log('Public reading, media hashes for 17 sources, guest isolation, mobile/touch and source fallback passed.');
}finally{await browser.close()}
