// Offline content authored in the current Codex session, explicitly authorized by the user.
// These authored artifacts are data for the shared Runtime, never topic templates in the host.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import type {AnswerArtifact,InteractiveBlock,TextBinding} from '../../src/lib/types';
const out='artifacts/astra-repair';await mkdir(out,{recursive:true});
const read=async(id:string)=>JSON.parse(await readFile('.data/handoffs/'+id+'.json','utf8'));
const code=(fn:Function)=>'const __name=(fn)=>fn;\n'+fn.toString().replace(/^[^{]*\{/,'').replace(/\}\s*$/,'');
const common=`body{padding:16px;color:var(--ink,#183a35);background:var(--paper,#f2f5ed)}h3,p{margin:0 0 12px}h3{font-size:21px;line-height:1.25}small,.note{font-size:12px;line-height:1.6;color:var(--muted,#526b62)}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:12px 0}button{border:1px solid currentColor;border-radius:6px;background:transparent;color:inherit;padding:8px 12px;min-height:42px}button[aria-pressed=true],button.primary{background:var(--ink,#183a35);color:var(--paper,#f2f5ed)}label{display:flex;flex-direction:column;font-size:12px;gap:4px;min-width:0}input[type=number],select{border:1px solid #9baaa2;background:#fff;color:#16332e;border-radius:4px;padding:8px;width:100%;min-width:0}input[type=range]{width:100%;accent-color:var(--ink,#183a35)}.controls{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.metrics{display:flex;flex-wrap:wrap;gap:16px;margin:14px 0}.metrics b{font-size:26px;line-height:1.2;display:block;font-variant-numeric:tabular-nums;white-space:nowrap}.metrics span{font-size:12px}.visual{display:block;width:100%;height:auto}output{display:block}button:disabled{opacity:.35}svg text{font-family:inherit}.note{margin-top:12px}[hidden]{display:none!important}@media(max-width:420px){body{padding:12px}.controls{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics b{font-size:23px}h3{font-size:19px}}`;
type B=InteractiveBlock&{purpose:string;operation:string};
const block=(id:string,anchor:string,title:string,html:string,js:Function,purpose:string,operation:string,css='',height=480):B=>({id,afterParagraphId:anchor,title,html,js:code(js),css:common+css,height,kind:'experience',purpose,operation});
const check=(blockId:string,selector:string,text:string,target='#status',action='click',value?:string)=>({blockId,selector,action,value,expect:{selector:target,text}});
async function save(id:string,intent:string,flow:string,blocks:B[],checks:any[],bindings:TextBinding[]=[],palette=['#183a35','#f2f5ed','#d98b51']){
 const h=await read(id);const artifact:any={version:1,answerId:id,explanation:intent,bindings,blocks:blocks.map(({purpose,operation,...b})=>b),scene:blocks.flatMap(b=>[{action:'focus',target:b.afterParagraphId,title:b.title,text:b.purpose},{action:'reveal',target:b.id,title:'亲手试一次',text:b.operation}]),design:{version:'session-repair-2026-09-14',intent,readingFlow:flow,voice:'原文保留；补充计算、示意与情景均在操作旁标注。',style:{palette,typography:'系统中文字体；指标等宽数字；窄屏指标整段换行。',surface:'每篇由其论点或叙事情境决定画面，操作反馈就在原文对应位置。',motion:'仅操作驱动；即时反馈；键盘、触摸和复位等价可用。'},decisions:[{title:'操作必须改变可见关系',reason:intent,tradeoff:'图示为解释论点服务，范围与缺失信息就地说明。'}],components:blocks.map(b=>({blockId:b.id,purpose:b.purpose,whyHere:'紧接对应原文：'+h.answer.source.paragraphs.find((p:any)=>p.id===b.afterParagraphId)?.text.slice(0,160),interaction:b.operation,implementation:'独立沙箱内 HTML、CSS 与 SVG；共享状态只经 world 协议。',checks:checks.filter(c=>c.blockId===b.id).slice(0,8).map(c=>c.selector+' → '+c.expect.text)}))}};
 await writeFile(out+'/'+id+'.json',JSON.stringify(artifact,null,2));await writeFile(out+'/'+id+'.checks.json',JSON.stringify(checks,null,2));
}

export {read,save,block,check,code};
