// Supplement actual acceptance with isolated, fully painted views and mechanism assertions.
import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {frameDocument} from '../../src/lib/runtime';
const dir='artifacts/reviews/astra-visual';await mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true});const results:any[]=[];
try{for(const width of [740,360]){const page=await browser.newPage({viewport:{width,height:1000},hasTouch:width===360});await page.route('http://inspect.local/',r=>r.fulfill({contentType:'text/html',body:'<body style="margin:0"><iframe id="target" sandbox="allow-scripts" style="width:100%;height:960px;border:0"></iframe></body>'}));
for(const file of (await readdir('src/data/generated')).filter(f=>f.endsWith('.json'))){const a=JSON.parse(await readFile('src/data/generated/'+file,'utf8'));const picked=a.artifact.blocks.filter((b:any,i:number)=>i===0||['threshold-view','door-encounter','cash-river','productivity-factory'].includes(b.id));for(const b of picked){await page.goto('http://inspect.local/');await page.evaluate(()=>{window.addEventListener('message',e=>{if(e.data?.type==='resize'){document.getElementById('target')!.style.height=e.data.value+'px'}})});await page.locator('#target').evaluate((f,doc)=>(f as HTMLIFrameElement).srcdoc=doc,frameDocument(b,b.id,'http://inspect.local',a.assets||[]));const frame=page.frameLocator('#target');await frame.locator('body').waitFor();await frame.locator('button').first().waitFor();
const label=file.replace('.json','')+'-'+b.id+'-'+width;await page.screenshot({path:dir+'/'+label+'.png',fullPage:true});
if(b.id==='threshold-view'){assert.equal(await frame.locator('.overlay').isVisible(),false);await frame.locator('#reader').click();assert.equal(await frame.locator('.overlay').isVisible(),true);await frame.locator('#her').press('Enter');assert.equal(await frame.locator('.overlay').isVisible(),false)}
if(b.id==='door-encounter'){assert.equal(await frame.locator('#audience-info').isVisible(),false);await frame.locator('#advance').click();const before=await frame.locator('svg').innerHTML();await frame.locator('#view').click();assert.equal(await frame.locator('#audience-info').isVisible(),true);assert.notEqual(await frame.locator('svg').innerHTML(),before);await frame.locator('#advance').click();assert.notEqual(await frame.locator('svg').innerHTML(),before);await frame.locator('#reset').click();assert.equal(await frame.locator('#audience-info').isVisible(),false)}
if(b.id==='productivity-factory'){await frame.locator('#growth').fill('150');const w=await frame.locator('svg rect').last().getAttribute('width');assert.ok(Number(w)<=600);assert.match(await frame.locator('#status').innerText(),/173\.08/)}
assert.equal(await frame.locator('body').evaluate(el=>el.scrollWidth>el.clientWidth+2),false,label);results.push({id:a.source.id,block:b.id,width,screenshot:label+'.png'});
}}await page.close()}}finally{await browser.close()}
await writeFile(dir+'/observations.json',JSON.stringify({checkedAt:new Date().toISOString(),results,mechanisms:['story information actually hides/reveals','story viewpoint changes SVG','story reset hides reader information','population upper boundary stays in frame']},null,2));console.log(results.length+' painted views and critical mechanism checks passed');
