<script lang="ts">
 import {realAnswersFirst} from '../src/lib/answer-order';
 import {readLocal,writeLocal} from '../src/lib/storage';
 import {selectInteractions} from '../src/lib/interaction-library';
 import {onMount} from 'svelte';
 import {richSource,plainSource,authorAvatar} from '../src/lib/rich-source';
 import ArtifactLinks from '../src/components/ArtifactLinks.svelte';
 import ReadingParagraph from '../src/components/ReadingParagraph.svelte';
 import {replacementBlock} from '../src/lib/block-media';
 let mediaStatus=$state<Record<string,boolean>>({}),sourceOnly=$state(false);
 import SourceTools from '../src/components/SourceTools.svelte';
 import WorldFrame from '../src/components/WorldFrame.svelte';
 import type {StudioAnswer} from './types';
 import {status} from './types';
 import type {AnswerVersion,AnswerSource} from '../src/lib/types';
 let items=$state<StudioAnswer[]>([]),current=$state<StudioAnswer>(),query=$state(''),filter=$state('全部'),message=$state('正在读取…'),error=$state(''),busy=$state(false);
 let title=$state(''),author=$state(''),url=$state(''),body=$state(''),parsed=$state<AnswerSource>(),versions=$state<AnswerVersion[]>([]),historical=$state<StudioAnswer>(),articleState=$state<Record<string,string>>({});
 let timer:ReturnType<typeof setTimeout>,queue=Promise.resolve(),backupQueue=Promise.resolve(),pendingJson='',dirty=$state(false);
 function backup(value:string){pendingJson=value;backupQueue=backupQueue.then(()=>writeLocal('studio-pending',value)).catch(()=>{error='浏览器草稿备份失败，请保持页面打开并重试后台保存'});return backupQueue}
 const copy=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
 async function api(path='',body?:unknown){const r=await fetch('/api/studio/'+path,{method:body?'POST':'GET',headers:{'X-Studio-Client':'yida-studio','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error);return d}
 async function load(){try{items=await api();message='已读取本地素材库'}catch(e){error=String(e)}}
 async function save(kind='draft'){
  clearTimeout(timer);if(!current)return;const snapshot=copy(current);dirty=true;void backup(JSON.stringify(snapshot));message='正在保存…';
  queue=queue.then(async()=>{try{const known=items.find(a=>a.source.id===snapshot.source.id);const saved=await api(snapshot.source.id,{answer:snapshot,expectedRevision:known?.workspace?.revision||0,kind});items=[saved,...items.filter(a=>a.source.id!==saved.source.id)];if(current&&current.source.id===saved.source.id){current.workspace!.revision=saved.workspace.revision;if(kind==='source'){current.artifact=saved.artifact;current.reference=saved.reference;current.studio.status=saved.studio.status}}
   if(pendingJson===JSON.stringify(snapshot)){void backup('');dirty=false}message='已保存到本地后台';error='';
  }catch(e){error=String(e);message='后台未保存 · 草稿保留在此浏览器';throw e}}).catch(()=>{});await queue;
 }
 function changed(){dirty=true;if(current)void backup(JSON.stringify(copy(current)));clearTimeout(timer);timer=setTimeout(()=>void save(),450)}
 async function choose(a?:StudioAnswer){if(dirty){await save();if(dirty)return}historical=undefined;articleState={};current=a?copy(a):undefined;title=a?.source.title||'';author=a?.source.author||'';url=a?.source.sourceUrl||'';body=a?.source.paragraphs.map(p=>p.text).join('\n\n')||'';parsed=a?copy(a.source):undefined;versions=[]}
 function paste(e:ClipboardEvent){const html=e.clipboardData?.getData('text/html'),text=e.clipboardData?.getData('text/plain')||'';if(!html&&!text)return;e.preventDefault();try{parsed=html?richSource(html,{method:'clipboard',title:title||undefined,author:author||undefined}):plainSource(text,{title:title||undefined,author:author||undefined});body=parsed.paragraphs.map(p=>p.text).join('\n\n');if(!title)title=parsed.title;if(!author)author=parsed.author;error=''}catch(e){error=String(e)}}
 async function saveSource(){try{const source=parsed?copy(parsed):plainSource(body,{title,author});source.title=title.trim()||source.title;source.author=author.trim()||'作者待核对';source.avatar=authorAvatar(source.author);source.sourceUrl=url.trim()||undefined;source.id=current?.source.id||'studio-'+crypto.randomUUID();const old=current?.source.paragraphs||[];const used=new Set<string>();source.paragraphs=source.paragraphs.map(p=>{const match=old.find(o=>!used.has(o.id)&&o.text===p.text&&o.html===p.html);const id=match?.id||'p-'+crypto.randomUUID();used.add(id);return {...p,id}});
 current=current?{...current,source}:{source,votes:0,accent:'#477866',tag:'精选回答',workspace:{revision:0,idea:'',selectedParagraphIds:[],updatedAt:''},studio:{notes:[],feedback:'',tags:[],status:'draft'}};await save('source');parsed=copy(source)}catch(e){error=String(e)}}
 async function history(){if(current){await save();versions=await api(current.source.id+'/versions')}}
 function addNote(id:string,text:string){if(!current)return;current.studio.notes.push({id:crypto.randomUUID(),paragraphId:id,quote:text,text:''});changed()}
 let visible=$derived(realAnswersFirst(items.filter(a=>(filter==='全部'||status(a)===filter)&&[a.source.title,a.workspace?.idea,...a.source.paragraphs.map(p=>p.text)].join(' ').includes(query))));
 let preview=$derived(historical||current);
 let recommendations=$derived(current?selectInteractions([current.source.title,current.workspace?.idea,...current.studio.tags,current.studio.feedback,...current.studio.notes.map(n=>n.text)].join(' ')):[]);
 onMount(()=>{void load();const prevent=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',prevent);return()=>{clearTimeout(timer);window.removeEventListener('beforeunload',prevent)}});
 async function recover(){const raw=await readLocal('studio-pending','');if(!raw)return;const a=JSON.parse(raw) as StudioAnswer;const latest=items.find(x=>x.source.id===a.source.id);if(latest&&latest.workspace?.revision!==a.workspace?.revision){error='后台版本已变化。请先复制草稿备注，再打开后台版本核对。';current=a;return}await choose(a);dirty=true;await save()}
</script>
<svelte:head><title>回答工作台 · 内部</title></svelte:head>
<header><div><small>LOCAL STUDIO / 内部工具</small><h1>把你的理解，变成可复用的表达。</h1></div><button onclick={()=>choose()}>＋ 粘贴新回答</button></header>
<div class="notice" role="status">{message} <button onclick={recover}>恢复未保存草稿</button><button onclick={async()=>{if(dirty){await save();if(dirty)return}await load();if(current)await choose(items.find(a=>a.source.id===current!.source.id))}}>刷新后台</button></div>
{#if error}<div class="error" role="alert">{error} <button onclick={()=>save()}>重试保存</button></div>{/if}
<main><aside><h2>回答素材 <span>{items.length}</span></h2><input aria-label="搜索回答" placeholder="搜索原文或想法" bind:value={query}/><select aria-label="处理状态" bind:value={filter}>{#each ['全部','待加工','待验收','待更新','已精选'] as s}<option>{s}</option>{/each}</select>{#each visible as a}<button class:chosen={current?.source.id===a.source.id} class="item" onclick={()=>choose(a)}><small>{status(a)}</small><strong>{a.source.title}</strong><span>{a.source.author} · {a.studio.notes.length} 条备注</span></button>{/each}{#if !items.length}<p>从第一篇回答开始，留下你想让读者看到和尝试的东西。</p>{/if}</aside>
<section class="editor"><h2>{current?'原文与设计想法':'录入一篇回答'}</h2><label>标题<input bind:value={title}/></label><label>作者<input bind:value={author}/></label><label>来源链接<input bind:value={url} placeholder="可选，仅记录出处"/></label><label>正文<textarea rows="7" bind:value={body} onpaste={paste} oninput={()=>parsed=undefined} placeholder="从知乎复制完整正文，在这里粘贴。富文本和图片会保留。"></textarea></label><button class="primary" onclick={saveSource}>保存原文</button><details class="import-help"><summary>支持的内容与大小限制</summary><p>支持粘贴纯文本或富文本正文、列表、表格和图片。图片可能需要在“原文与离线保存”中补全。</p><p>暂不支持直接导入 PDF、Word 或截图识字；网页中的脚本不会执行，绘图和嵌入播放器需补充原始内容。</p><p>标题最多 160 字符，作者最多 80 字符；正文最多 100 万字符，富文本最多 4 MB。整体想法和每条备注最多 2 万字符。</p></details>
{#if current}<label>整体可视化想法<textarea rows="5" bind:value={current.workspace!.idea} oninput={changed} placeholder="希望读者理解什么？可以怎样交互？"></textarea></label><label>匹配标签<input value={current.studio.tags.join('，')} oninput={e=>{current!.studio.tags=e.currentTarget.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);changed()}} placeholder="比较、参数实验、逐步推导…"/></label><label>预览后的反馈<textarea rows="4" bind:value={current.studio.feedback} oninput={changed} placeholder="满意之处、问题、下一轮修改方向"></textarea></label><details><summary>相关经验与可改编组件 · {recommendations.length}</summary>{#each recommendations as recipe}<div class="note"><strong>{recipe.title} · v{recipe.version}</strong><p>{recipe.goal}</p><p>适用：{recipe.when}</p><p>注意：{recipe.avoid}</p></div>{/each}{#if !recommendations.length}<p>写下想法或标签后，会匹配已有交互；不匹配时可新创作。</p>{/if}</details><h3>段落备注</h3><p>在右侧正文下点击“给这段加备注”。</p>{#each current.studio.notes as n}<div class="note"><blockquote>{n.quote}</blockquote>{#if !current.source.paragraphs.some(p=>p.id===n.paragraphId&&p.text===n.quote)}<strong class="error">原段落已变化，请重新关联</strong><select aria-label="重新关联段落" onchange={e=>{const p=current!.source.paragraphs.find(p=>p.id===e.currentTarget.value);if(p){n.paragraphId=p.id;n.quote=p.text;changed()}}}><option value="">选择新段落</option>{#each current.source.paragraphs as p}<option value={p.id}>{p.text.slice(0,65)}</option>{/each}</select>{/if}<textarea aria-label="段落备注" bind:value={n.text} oninput={changed}></textarea><button onclick={()=>{current!.studio.notes=current!.studio.notes.filter(x=>x.id!==n.id);changed()}}>删除备注</button></div>{/each}<SourceTools answer={current} onassets={assets=>{current!.assets=assets;void save('media')}}/><button onclick={history}>查看版本历史</button>{#each versions as v}<button class="version" onclick={async()=>{historical=await api(current!.source.id+'/versions/'+v.id);articleState={}}}>{v.createdAt} · {v.kind}</button>{/each}<p class="handoff">交给助手加工：<code>npm run studio -- export --id {current.source.id}</code></p>{/if}</section>
<section class="preview"><h2>阅读效果预览</h2><label><input type="checkbox" bind:checked={sourceOnly}/> 只看原文</label>{#if preview}{#if historical}<p class="banner">正在查看历史版本 <button onclick={()=>{historical=undefined;articleState={}}}>回到当前版本</button></p>{/if}{#if preview.reference}<p class="banner">原文已更新，旧效果保留在历史中，等待重新加工。</p>{/if}<h1>{preview.source.title}</h1>{#if preview.artifact?.libraryReferences?.length}<details><summary>本版组件使用记录</summary>{#each preview.artifact.libraryReferences as ref}<p>{ref.id} · v{ref.version} · {ref.mode==='reuse'?'直接复用':'改编'}：{ref.changes}</p>{/each}</details>{/if}<p>{preview.source.author}</p><ArtifactLinks artifact={preview.artifact}/>{#each preview.source.paragraphs as p}<ReadingParagraph paragraph={p} assets={preview.assets} folded={!sourceOnly&&!!mediaStatus[(preview.artifact?.provenance.runId||'')+(replacementBlock(preview.artifact,p.id)?.id||'')]}/>{#if !historical}<button class="annotate" onclick={()=>addNote(p.id,p.text)}>＋ 给这段加备注</button>{/if}{#each preview.artifact?.bindings.filter(b=>b.paragraphId===p.id&&!b.hidden)||[] as b}<p>{b.label}：{articleState[b.id]??b.initial}</p>{/each}{#each (sourceOnly?[]:preview.artifact?.blocks.filter(b=>b.afterParagraphId===p.id)||[]) as block}{#key preview.artifact?.provenance.runId+block.id}<WorldFrame {block} assets={preview.assets} onstatus={ok=>mediaStatus={...mediaStatus,[preview!.artifact!.provenance.runId+block.id]:ok}} articleState={{...Object.fromEntries(preview.artifact!.bindings.map(b=>[b.id,b.initial])),...articleState}} onbinding={(k,v)=>{if(preview?.artifact?.bindings.some(b=>b.id===k))articleState={...articleState,[k]:v}}}/>{/key}{/each}{/each}{:else}<div class="empty">先保存原文，然后记录你的设计方向。<br/>助手加工后，完整交互将在这里呈现。</div>{/if}</section></main>
<style>
 :global(body){margin:0;background:#f4f3ef;color:#263d35;font-family:system-ui,sans-serif;font-size:14px} :global(*){box-sizing:border-box}header{padding:30px 36px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #d9dfd8}small{font-size:11px;letter-spacing:1px;color:#688576}h1{font-size:23px;font-weight:600}h2{font-size:17px}button,input,textarea,select{font:inherit}button{cursor:pointer;background:#fff;border:1px solid #ccd6ce;border-radius:7px;padding:9px 12px;color:inherit}button:hover{background:#e6eee7}input[type=checkbox]{width:auto;margin-right:8px}input:not([type=checkbox]),textarea,select{width:100%;padding:10px;border:1px solid #ccd6ce;border-radius:6px;background:#fff;color:#253b32}textarea{resize:vertical;line-height:1.7}label{display:block;margin:15px 0;line-height:2}.notice,.error{padding:10px 36px}.notice button{padding:4px 9px;margin-left:8px}.error{color:#a03625;background:#fff1e9}main{display:grid;grid-template-columns:235px minmax(300px,1fr) minmax(360px,1.3fr);min-height:80vh}aside,.editor,.preview{padding:24px;border-right:1px solid #d9dfd8}.preview{background:#fff;line-height:1.9;min-width:0}.preview :global(img){max-width:100%}.preview :global(iframe){width:100%;border:0}.item{display:grid;gap:9px;text-align:left;width:100%;margin-top:12px}.item span{font-size:12px;color:#6b7f73}.chosen{border-color:#367254;background:#e9f1e9}.primary{background:#315f49;color:white}.annotate{padding:3px 8px;font-size:12px;color:#718777;border-style:dashed}.note{padding:12px;background:#e9eee7;margin:12px 0}.note blockquote{margin:0 0 8px;font-size:12px;max-height:75px;overflow:auto}.version{display:block;width:100%;margin:8px 0}.handoff{overflow-wrap:anywhere;color:#69796b}.empty{padding:70px 0;color:#829084}.banner{background:#eef2e7;padding:12px}aside select{margin-top:10px}@media(max-width:1000px){main{grid-template-columns:190px 1fr}.preview{grid-column:1/-1}}@media(max-width:600px){main{display:block}header{padding:20px;display:block}}
</style>
