import {sqliteTable,text,integer,primaryKey,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),name:text('name').notNull(),avatar:text('avatar').notNull(),createdAt:text('created_at').notNull()});
export const sessions=sqliteTable('sessions',{hash:text('hash').primaryKey(),userId:text('user_id').notNull(),expires:integer('expires').notNull()});
export const oauthStates=sqliteTable('oauth_states',{hash:text('hash').primaryKey(),browserHash:text('browser_hash').notNull(),expires:integer('expires').notNull()});
export const documents=sqliteTable('documents',{owner:text('owner').notNull(),id:text('id').notNull(),revision:integer('revision').notNull(),bodyKey:text('body_key').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.owner,t.id]})]);
export const versions=sqliteTable('versions',{owner:text('owner').notNull(),id:text('id').notNull(),revision:integer('revision').notNull(),bodyKey:text('body_key').notNull(),kind:text('kind').notNull(),title:text('title').notNull(),instruction:text('instruction').notNull(),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.owner,t.id,t.revision]})]);
export const jobs=sqliteTable('jobs',{id:text('id').primaryKey(),owner:text('owner').notNull(),day:text('day').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),fingerprint:text('fingerprint').notNull(),sourceId:text('source_id').notNull(),sourceHash:text('source_hash').notNull(),bodyKey:text('body_key').notNull(),repairs:integer('repairs').notNull().default(0),lease:text('lease'),leaseUntil:integer('lease_until'),error:text('error'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('jobs_fingerprint').on(t.kind,t.fingerprint)]);
export const sources=sqliteTable('sources',{id:text('id').primaryKey(),hash:text('hash').notNull(),bodyKey:text('body_key').notNull(),fetchedAt:text('fetched_at').notNull()});
export const discussions=sqliteTable('discussions',{id:text('id').primaryKey(),title:text('title').notNull(),summary:text('summary').notNull(),url:text('url').notNull(),fetchedAt:text('fetched_at').notNull(),publishedAt:text('published_at')});
