// Offline authoring record for the explicitly authorized Codex session.
// This file is never imported by the product or a model endpoint.
import {mkdir,writeFile} from 'node:fs/promises';
import type {AnswerArtifact,DesignBaseline,InteractiveBlock} from '../src/lib/types';

const css=`body{padding:16px 2px;color:#253849;font-size:15px}h3{font-size:19px;line-height:1.4;margin:0 0 16px}p{margin:12px 0;line-height:1.65}.muted{color:#556b7c;font-size:14px}.controls{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:12px 0 18px}button{border:1px solid #b6c8d5;background:#fff;color:#1d536f;border-radius:5px;padding:7px 12px;min-height:40px}button.primary{background:#17638a;color:#fff;border-color:#17638a}input[type=number]{width:80px;border:1px solid #8fa7b8;border-radius:4px;padding:6px;color:#172f40;background:#fff}input[type=range]{accent-color:#17638a;max-width:100%;width:180px}label{display:flex;align-items:center;gap:8px;flex-wrap:wrap}strong.number{display:block;font-size:30px;line-height:1.3;color:#174e72;font-variant-numeric:tabular-nums;margin:10px 0}.columns{display:grid;grid-template-columns:1fr 1fr;gap:18px}.column{border-top:2px solid #a4bac9;padding-top:12px;min-width:0}.column p{margin:6px 0}.formula{font-family:ui-monospace,monospace;font-size:14px;overflow-wrap:anywhere}.note{border-left:3px solid #a4bac9;padding:8px 12px;background:#f3f7fa}.result{font-size:17px;color:#164f71;font-weight:600}.meter{height:14px;background:#e4edf3;position:relative;border-radius:2px;margin:8px 0}.meter span{display:block;height:100%;background:#32759b}.meter i{position:absolute;top:-4px;bottom:-4px;width:2px;background:#243848;left:50%}.legend{display:flex;gap:14px;flex-wrap:wrap;font-size:14px}.legend span:before{content:'';display:inline-block;width:12px;height:12px;background:#32759b;margin-right:5px}.legend .work{background:transparent}.legend .work:before{background:#b89950}.bar{display:flex;height:22px;background:#eef2f5;margin:8px 0 4px}.wait{background:#32759b}.work{background:#b89950}.bar-label{display:flex;justify-content:space-between;gap:10px}.bar-label b{font-variant-numeric:tabular-nums}.settings{display:grid;gap:10px}.settings label{justify-content:space-between;max-width:420px}input[type=checkbox]{width:18px;height:18px;accent-color:#17638a}.check{align-items:flex-start;flex-wrap:nowrap}output{font-variant-numeric:tabular-nums}@media(max-width:430px){.columns{gap:12px}.column{font-size:14px}strong.number{font-size:27px}.controls{gap:8px}body{padding:12px 2px}h3{font-size:18px}}`;
const component=(blockId:string,purpose:string,whyHere:string,interaction:string,implementation:string,checks:string[])=>({blockId,purpose,whyHere,interaction,implementation,checks});
const design=(intent:string,readingFlow:string,components:DesignBaseline['components']):DesignBaseline=>({
  version:'explanation-v3.2026-09-07',intent,readingFlow,voice:'用可核对的计算与实验解释原文，保留作者的简洁语气。',
  style:{palette:['#253849','#17638a','#b89950','#f3f7fa'],typography:'正文15px，标签至少14px，关键结果27–30px；公式与数值使用等宽或表格数字。',surface:'平面排版、细分隔线与共用刻度，把空间留给参数、结论和适用范围。',motion:'参数变化立即更新；实验由点击触发，无循环动画。'},
  decisions:[{title:'先让计算关系可比较',reason:'用户要求提高信息含量。旧版物件场景占据空间，却限制了对假设和结论的检验；本轮保留原文与有效公式，重新组织交互。',tradeoff:'减少物件操作的趣味，换取同一眼能核对的输入、结果和依据。'},{title:'让第二处交互检验第一处结论',reason:readingFlow,tradeoff:'通过声明的共享状态保持参数一致，不重复设置；随机实验明确区别于理论值，假设扩展明确标注。'}],components});

const birthdayBlocks:InteractiveBlock[]=[{
  id:'birthday-compare',afterParagraphId:'birthday-p1',title:'同样的人数，两个不同的问题',kind:'figure',height:450,css,
  html:`<h3>同样的人数，两个不同的问题</h3><div class="controls"><label>总人数 n（包括我）<input id="n" type="number" min="2" max="60" value="23"></label><button id="reset" type="button">回到 23 人</button><button id="fifty" type="button">试试 50 人</button></div><div class="columns" aria-live="polite"><div class="column"><b>任意两人同日</b><strong class="number" id="any">50.7%</strong><p><span id="pairs">253</span> 对可比较的人</p><div class="meter"><span id="anybar"></span></div><p class="formula">1 − ∏(1 − i/365)<br>i 从 0 到 n−1</p></div><div class="column"><b>至少一人与我同日</b><strong class="number" id="me">5.9%</strong><p><span id="others">22</span> 人分别与我比较</p><div class="meter"><span id="mebar"></span></div><p class="formula">1 − (364/365)<sup>n−1</sup></p></div></div><p class="note">两两组合数增长更快，但各对是否同日并不相互独立。不能直接把“组合数 ÷ 365”当成概率。</p><p class="muted">沿用原文假设：生日独立、365 天等可能、忽略闰日。下方实验跟随这里的人数。</p>`,
  js:`const q=s=>document.querySelector(s);let n=23,last='';function draw(){const value=Number(q('#n').value);n=Math.max(2,Math.min(60,Number.isFinite(value)?Math.round(value):23));q('#n').value=String(n);let unique=1;for(let i=0;i<n;i++)unique*=1-i/365;const any=1-unique,me=1-Math.pow(364/365,n-1);q('#any').textContent=(any*100).toFixed(1)+'%';q('#me').textContent=(me*100).toFixed(1)+'%';q('#pairs').textContent=String(n*(n-1)/2);q('#others').textContent=String(n-1);q('#anybar').style.width=any*100+'%';q('#mebar').style.width=me*100+'%';if(String(n)!==last){last=String(n);world.emit('birthday-n',last)}}q('#n').addEventListener('input',()=>{if(q('#n').value!=='')draw()});q('#n').addEventListener('change',draw);q('#reset').addEventListener('click',()=>{q('#n').value='23';draw()});q('#fifty').addEventListener('click',()=>{q('#n').value='50';draw()});draw();`
},{
  id:'birthday-experiment',afterParagraphId:'birthday-p2',title:'理论概率，会怎样出现在重复实验中？',kind:'experience',height:430,css,
  html:`<h3>理论概率，会怎样出现在重复实验中？</h3><p>每轮随机生成 <b id="n-label">23</b> 个人的生日，记录是否有重复日期。</p><div class="controls"><button id="run" class="primary" type="button">再做 1000 轮</button><button id="clear" type="button">清空实验</button></div><div class="columns" aria-live="polite"><div class="column"><b>理论概率</b><strong class="number" id="theory">50.7%</strong><p>由上方公式计算</p></div><div class="column"><b>实验频率</b><strong class="number" id="observed">尚未实验</strong><p id="count">0 轮 · 0 轮出现同日</p></div></div><p id="latest" class="muted">点击开始，理论值不会随某次随机结果改变。</p><div class="meter" aria-hidden="true"><span id="observedbar" style="width:0"></span><i id="theorymark"></i></div><p class="muted">蓝色长度为实验频率；深色刻线为理论概率。范围 0–100%。</p><p id="difference" class="note">每次点击做 1000 轮，最多 10000 轮。改变人数会清空旧实验，避免混用不同假设。</p>`,
  js:`const q=s=>document.querySelector(s);let n=23,total=0,hits=0,lastBatch=0;function theory(){let p=1;for(let i=0;i<n;i++)p*=1-i/365;return 1-p}function draw(){const p=theory();q('#n-label').textContent=String(n);q('#theory').textContent=(p*100).toFixed(1)+'%';q('#observed').textContent=total?(100*hits/total).toFixed(1)+'%':'尚未实验';q('#count').textContent=total+' 轮 · '+hits+' 轮出现同日';q('#observedbar').style.width=(total?100*hits/total:0)+'%';q('#theorymark').style.left=100*p+'%';q('#run').disabled=total>=10000;q('#latest').textContent=total?'最近 1000 轮：'+lastBatch+' 轮出现同日。':'点击开始，理论值不会随某次随机结果改变。';q('#difference').textContent=total?'本次累计频率与理论值相差 '+Math.abs(100*hits/total-100*p).toFixed(1)+' 个百分点。重复实验通常有助于看出概率规律，但不保证每一批都更接近理论值。':'每次点击做 1000 轮，最多 10000 轮。改变人数会清空旧实验，避免混用不同假设。'}function reset(){total=0;hits=0;lastBatch=0;draw()}q('#run').addEventListener('click',()=>{if(total>=10000)return;lastBatch=0;for(let trial=0;trial<1000;trial++){const seen=new Set();let collision=false;for(let i=0;i<n;i++){const day=Math.floor(Math.random()*365);if(seen.has(day)){collision=true;break}seen.add(day)}if(collision)lastBatch++}total+=1000;hits+=lastBatch;draw()});q('#clear').addEventListener('click',reset);world.onState(state=>{const next=Number(state['birthday-n']);if(Number.isInteger(next)&&next>=2&&next<=60&&next!==n){n=next;reset()}});draw();`
}];
const birthday={version:1,answerId:'birthday',explanation:'先把两个常被混淆的问题并排计算，让人数、比较对数和概率互相对照；再把同一人数交给重复随机实验，观察实验频率与理论值的差异。保留原文假设与推导依据，减少场景装饰，让每次操作都能检验一句具体结论。',blocks:birthdayBlocks,
  bindings:[{id:'birthday-n',paragraphId:'birthday-p1',label:'实验人数',initial:'23',hidden:true}],
  scene:[{action:'focus',target:'birthday-p0',title:'先确认概率成立的条件',text:'原文的独立、均匀和365天假设决定后续计算。这里保留原文，避免把结论扩大到任何生日分布。'},{action:'reveal',target:'birthday-compare',title:'让两个问题同时可见',text:'同样23人，任意两人约50.7%，有人与我同日约5.9%。并排显示，避免切换时记错比较对象。',demo:{event:'click',selector:'#reset'}},{action:'highlight',target:'birthday-compare',title:'人数怎样改变比较机会？',text:'50人有1225对，但只需比较49人与我是否同日。公式计算概率，组合数负责解释增长。',demo:{event:'click',selector:'#fifty'}},{action:'reveal',target:'birthday-experiment',title:'一次实验不能替代理论',text:'沿用上方50人，真正随机运行1000轮。结果每次不同；理论值由公式确定。',demo:{event:'click',selector:'#run'}},{action:'highlight',target:'birthday-experiment',title:'再积累一批证据',text:'累计2000轮，观察频率变化。差距可能暂时增大，界面不会声称每次都更接近理论。',demo:{event:'click',selector:'#run'}},{action:'restore',target:'birthday-compare',title:'回到原文的23人',text:'重置人数后，下方清空50人的实验，防止不同假设混算。',demo:{event:'click',selector:'#reset'}}],
  design:design('让读者分清两个概率问题，并把理论推导与重复随机观察对应起来。','原文给出假设 → 第二段后比较两种事件及增长关系 → 末段后用相同人数做重复实验。',[
    component('birthday-compare','同一人数下对照事件、比较对数、公式和结果。','先读完原文对任意两人与我的区分，再把两种事件并排核对。','修改人数2–60或选择23/50，两个概率同步更新，下方实验跟随人数。','无碰撞概率连乘取补集；与我同日用独立事件补集；仅发出变化的人数。',['23人：253对、22人，50.7%与5.9%。','50人：1225对、49人，97.0%与12.6%。','2与60边界可用；320px无横向溢出。']),
    component('birthday-experiment','让读者区别理论值和随机样本频率。','原文最后邀请重复实验，此处直接积累可检查的实验轮数。','每次运行1000轮，累计最多10000；显示碰撞次数、频率、理论标记和差值；人数变化清空。','最多1000×60次抽样，碰撞提前结束；总量封顶；状态通过声明的birthday-n绑定传递。',['点击后1000轮，频率=碰撞次数/1000；理论值不变。','改人数会清零，重置有效，10000轮后按钮禁用。'])])
};

const redisBlocks:InteractiveBlock[]=[{
  id:'redis-compare',afterParagraphId:'redis-p1',title:'相同的命令，等待占了多少？',kind:'figure',height:570,css,
  html:`<h3>相同的命令，等待占了多少？</h3><div class="settings"><label>命令数 n<input id="commands" type="number" min="1" max="30" value="6"></label><label>一次往返 RTT（ms）<input id="rtt" type="number" min="1" max="200" value="80"></label><label>每条处理 p（ms）<input id="processing" type="number" min="1" max="50" value="2"></label></div><div class="controls"><button id="original" type="button">原文参数</button><button id="low" type="button">低延迟假设</button><button id="heavy" type="button">处理较重假设</button></div><div class="legend"><span>等待往返</span><span class="work">处理命令</span></div><div aria-live="polite"><p class="bar-label">逐条等待 <b id="serial">492 ms</b></p><div class="bar" aria-hidden="true"><span class="wait" id="serial-wait"></span><span class="work" id="serial-work"></span></div><p class="formula" id="serial-formula"></p><p class="bar-label">一批发送 <b id="pipeline">92 ms</b></p><div class="bar" aria-hidden="true"><span class="wait" id="pipe-wait"></span><span class="work" id="pipe-work"></span></div><p class="formula" id="pipe-formula"></p><p id="saving" class="result"></p></div><p class="note">两条横条使用同一刻度。处理的命令数相同，减少的是等待往返次数。此处假设命令独立、单批串行处理，无额外开销；参数是演示假设，并非实测。</p>`,
  js:`const q=s=>document.querySelector(s);let last='';function bounded(id,max){const input=q(id),value=Number(input.value);const result=Math.min(max,Math.max(1,Number.isFinite(value)?Math.round(value):1));input.value=String(result);return result}function draw(){const n=bounded('#commands',30),rtt=bounded('#rtt',200),p=bounded('#processing',50),work=n*p,serial=n*rtt+work,pipeline=rtt+work;q('#serial').textContent=serial+' ms';q('#pipeline').textContent=pipeline+' ms';q('#serial-formula').textContent=n+' × '+rtt+' + '+n+' × '+p+' = '+serial+' ms';q('#pipe-formula').textContent=rtt+' + '+n+' × '+p+' = '+pipeline+' ms';q('#serial-wait').style.width=(n*rtt/serial*100)+'%';q('#serial-work').style.width=(work/serial*100)+'%';q('#pipe-wait').style.width=(rtt/serial*100)+'%';q('#pipe-work').style.width=(work/serial*100)+'%';q('#saving').textContent='省去 '+(n-1)+' 次往返，节省 '+(serial-pipeline)+' ms；用时比 '+(serial/pipeline).toFixed(2)+' 倍。';const value=JSON.stringify({n,rtt,p});if(last!==value){last=value;world.emit('pipeline-assumptions',value)}}for(const id of ['#commands','#rtt','#processing']){q(id).addEventListener('input',()=>{if(q(id).value!=='')draw()});q(id).addEventListener('change',draw)}function preset(rtt,p){q('#commands').value='6';q('#rtt').value=String(rtt);q('#processing').value=String(p);draw()}q('#original').addEventListener('click',()=>preset(80,2));q('#low').addEventListener('click',()=>preset(1,2));q('#heavy').addEventListener('click',()=>preset(10,50));draw();`
},{
  id:'redis-boundary',afterParagraphId:'redis-p2',title:'分几批，以及何时不能合成一批',kind:'aside',height:440,css,
  html:`<h3>分几批，以及何时不能合成一批</h3><p id="assumptions" class="muted">沿用上方：6 条命令，RTT 80 ms，每条处理 2 ms。</p><div class="controls"><label>每批最多 b 条<input id="batch" type="range" min="1" max="6" value="6"><output id="batch-value">6</output></label><button id="reset" type="button">恢复全部一批</button></div><label class="check"><input id="dependent" type="checkbox"><span>改一个前提：下一条命令必须使用上一条返回的结果</span></label><div aria-live="polite"><p class="result" id="total">1 次往返，共 92 ms</p><p class="formula" id="formula"></p><p id="reason" class="note"></p></div><p class="muted">这是对原文独立命令假设的延伸：按批等待、每批一次 RTT、所有命令串行处理。真实 Pipeline 还受网络、缓冲和服务端影响，不能用这组数值替代压测。</p>`,
  js:`const q=s=>document.querySelector(s);let n=6,rtt=80,p=2;function draw(){q('#batch').max=String(n);const b=Math.min(n,Math.max(1,Math.round(Number(q('#batch').value)||1)));q('#batch').value=String(b);q('#batch-value').textContent=String(b);const dependent=q('#dependent').checked,effective=dependent?1:b,rounds=Math.ceil(n/effective),total=rounds*rtt+n*p;q('#batch').disabled=dependent;q('#assumptions').textContent='沿用上方：'+n+' 条命令，RTT '+rtt+' ms，每条处理 '+p+' ms。';q('#total').textContent=rounds+' 次往返，共 '+total+' ms';q('#formula').textContent='⌈'+n+' / '+effective+'⌉ × '+rtt+' + '+n+' × '+p+' = '+total+' ms';q('#reason').textContent=dependent?'下一条内容要等上一条结果才能确定，当前假设下只能逐条等待。取消勾选，回到原文的独立命令。':'每批最多 '+b+' 条，需要 '+rounds+' 批。命令仍是 '+n+' 条，处理总量仍为 '+(n*p)+' ms。'}q('#batch').addEventListener('input',draw);q('#dependent').addEventListener('change',draw);q('#reset').addEventListener('click',()=>{q('#dependent').checked=false;q('#batch').value=String(n);draw()});world.onState(state=>{if(!state['pipeline-assumptions'])return;const next=JSON.parse(state['pipeline-assumptions']);if(!Number.isInteger(next.n)||next.n<1||next.n>30||!Number.isInteger(next.rtt)||next.rtt<1||next.rtt>200||!Number.isInteger(next.p)||next.p<1||next.p>50)return;if(n===next.n&&rtt===next.rtt&&p===next.p)return;n=next.n;rtt=next.rtt;p=next.p;q('#batch').max=String(n);q('#batch').value=String(n);q('#dependent').checked=false;draw()});draw();`
}];
const redis={version:1,answerId:'redis',explanation:'沿用原文的时间公式，把往返等待和处理命令画在同一刻度上，允许修改假设以观察收益来源。再用批次大小和前后依赖检验适用边界。所有数字都能由显示的公式核对，明确区分演示计算与真实压测。',blocks:redisBlocks,
  bindings:[{id:'pipeline-assumptions',paragraphId:'redis-p1',label:'共同参数',initial:'{"n":6,"rtt":80,"p":2}',hidden:true}],
  scene:[{action:'focus',target:'redis-p0',title:'先找出独立命令与两个时间成本',text:'保留原文假设。处理与往返是不同成本，后续比较必须保持命令数量相同。'},{action:'reveal',target:'redis-compare',title:'492与92是怎样算出来的',text:'共同刻度下，金色处理部分长度相同，蓝色等待减少400ms。公式紧跟横条，避免只记住加速倍数。',demo:{event:'click',selector:'#original'}},{action:'highlight',target:'redis-compare',title:'网络已经很快时，还能省多少',text:'RTT改为1ms：逐条18ms，一批13ms，节省5ms。收益依赖假设，不能把原文倍数套到所有情况。',demo:{event:'click',selector:'#low'}},{action:'restore',target:'redis-compare',title:'用原文参数继续检验批次',text:'恢复6条、80ms、2ms，下方自动同步参数。',demo:{event:'click',selector:'#original'}},{action:'reveal',target:'redis-boundary',title:'两条一批，等待几次',text:'6条分成3批：3×80+6×2=252ms。减少往返与减少命令可以明确区分。',demo:{event:'input',selector:'#batch',value:'2'}},{action:'highlight',target:'redis-boundary',title:'下一条必须等待上一条结果呢',text:'依赖返回结果时，当前客户端假设只能逐条等待，总计492ms。这个操作让独立命令的前提变得可检验。',demo:{event:'click',selector:'#dependent'}},{action:'restore',target:'redis-boundary',title:'回到原文的适用范围',text:'恢复独立命令且全部一批，92ms。真实压测的网络、缓冲和工作量仍需要另行测量。',demo:{event:'click',selector:'#reset'}}],
  design:design('让读者核对Pipeline节省的是往返等待，并检验收益的参数与依赖边界。','原文定义命令与成本 → 公式之后同刻度拆分两种耗时 → 末段之后改变批次与依赖检验适用范围。',[
    component('redis-compare','相同工作量下拆开等待和处理，计算节省时间的来源。','先读完原文两种公式，再通过可修改参数核对公式。','修改命令数、RTT、处理时间或切换假设，横条、公式和下方边界工具同步。','整数有界输入；串行n×RTT+n×p，一批RTT+n×p；横条都除以串行总时间。',['原文参数492/92ms，节省400ms，处理部分都为12ms。','低延迟18/13ms；处理较重360/310ms；1条时两者相等。','320px无溢出，公式和完整数值可见。']),
    component('redis-boundary','检验批次大小与结果依赖如何改变往返数。','原文强调真实性能限制，此处用明确标注的简化延伸解释一个适用边界。','批次1–n；依赖选项使有效批次为1；恢复按钮回到独立且一批。','往返数ceil(n/b)；共享参数仅从声明binding读取，参数变化重置批次和依赖。',['原文参数b=2为252ms，b=1为492ms，b=6为92ms。','勾选返回依赖后492ms，解除/重置恢复批量；上方参数同步。'])])
};
await mkdir('artifacts/session/v3',{recursive:true});
for(const artifact of [birthday,redis])await writeFile('artifacts/session/v3/'+artifact.answerId+'.json',JSON.stringify(artifact,null,2));
console.log('Saved two actual Codex-session authored artifacts. Record provenance and verify in the shared runtime before promotion.');
