import {readFile,writeFile} from 'node:fs/promises';
import {parseFragment,serialize} from 'parse5';
import {StudioStore} from '../studio/store';
import {richText,sanitizeRichHTML} from '../src/lib/rich-source';
import type {StudioAnswer} from '../studio/types';
const db=new StudioStore('.data/studio.sqlite');
function pieces(text:string){const chunks:string[]=[];let start=0;while(text.length-start>800){let end=-1;for(let i=start+400;i<Math.min(text.length,start+800);i++)if(/[。！？\n]/.test(text[i]))end=i+1;if(end<0)break;chunks.push(text.slice(start,end));start=end}chunks.push(text.slice(start));return chunks}
function sliceHTML(html:string,start:number,end:number){let offset=0;const root=parseFragment(html) as any;function keep(n:any):boolean{if(n.nodeName==='#text'){const from=offset;offset+=n.value.length;n.value=n.value.slice(Math.max(0,start-from),Math.max(0,end-from));return !!n.value}n.childNodes=(n.childNodes||[]).filter(keep);return n.childNodes.length>0}root.childNodes=root.childNodes.filter(keep);return sanitizeRichHTML(serialize(root))}
try{for(const a of await db.list() as StudioAnswer[]){const source=structuredClone(a.source),changes:{paragraphId:string;replacementIds:string[];reason:string}[]=[];source.paragraphs=source.paragraphs.flatMap(p=>{if(p.text.length<1500)return[p];const html=p.html;if(html&&(!/^<p>/.test(html)||/<(?:img|br|table|math|hr|ul|ol)\b/.test(html)||richText(html)!==p.text))return[p];const parts=pieces(p.text);if(parts.length<2)return[p];let start=0;const out=parts.map((part,i)=>{const id=i?p.id+'-part-'+(i+1):p.id;const h=html?sliceHTML(html,start,start+part.length):undefined;start+=part.length;return {id,text:h?richText(h):part.trim(),...(h?{html:h}:{})}});if(out.some(p=>!p.text))return[p];changes.push({paragraphId:p.id,replacementIds:out.map(p=>p.id),reason:'按完整句子拆分超长段落，保持文字顺序与富文本强调，便于随文阅读与备注定位。'});return out});if(changes.length){const file='.data/cleanup-plans/'+source.id+'-paragraphs.json';await writeFile(file,JSON.stringify({id:source.id,expectedRevision:a.workspace!.revision,source,changes},null,2));console.log(file)}}}finally{db.close()}
