import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {Readable} from 'node:stream';
import {parse} from 'dotenv';
// This local preview executes the exact built Worker with server-only credentials.
// @ts-ignore production bundle is generated by npm run build
const {default:worker}=await import('../dist/server/index.js');
const port=Number(process.env.PRODUCTION_PREVIEW_PORT||4217);
createServer(async(req,res)=>{
 try{
  const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(chunk);
  const controller=new AbortController();res.on('close',()=>controller.abort());
  const request=new Request('http://127.0.0.1:'+port+req.url,{method:req.method,headers:req.headers as Record<string,string>,body:['GET','HEAD'].includes(req.method||'GET')?undefined:Buffer.concat(chunks),signal:controller.signal});
  const response=await worker.fetch(request,parse(readFileSync('.dev.vars')),{waitUntil:(p:Promise<unknown>)=>void p.catch(()=>{})});
  res.writeHead(response.status,Object.fromEntries(response.headers));
  if(response.body)Readable.fromWeb(response.body as any).pipe(res);else res.end();
 }catch{if(!res.headersSent)res.writeHead(500);res.end('Production preview failed')}
}).listen(port,'127.0.0.1',()=>console.log('Local production preview: http://127.0.0.1:'+port));
