import {readFile,writeFile,mkdir} from 'node:fs/promises';import {parse} from 'dotenv';import {generateArtifact} from '../server/generation';
const env=parse(await readFile('.dev.vars','utf8')),id='studio-3d0c8ad5-ea44-4f61-9530-f086b7135a6f',dir='artifacts/release-upgrades/'+id+'/v7';await mkdir(dir,{recursive:true});const h=JSON.parse(await readFile('.data/handoffs/'+id+'.json','utf8'));
const input={source:h.answer.source,selectedParagraphIds:[],tier:'balanced' as const,instruction:`重新设计现金流的两段交互，仅两个块，避免增加不准确的房价小游戏。
1.工资条：原文15元/小时、12小时/天、365天/年=65700。三个number输入可以改，复位；把年收入传给下一块。
2.现金流时间轴：收入65700、支出0、g=0%、n=30、r=4%；4%和支出0明确是演示假设，不是原文缺失值。首年净收入=(收入-支出)，每年净收入=首年净收入*(1+g)^(t-1)，PV=sum(net_t/(1+r)^t)。年末支付；1年4%现值为63173.08，不是65700。0%/0增长30年为1971000，4%30年约1136087。可以改收入、支出、增长、年限、折现率，显示名义累计与现值。逐年可点击的两类柱形或票据视觉，负现金流向下；前后年按钮与逐年表。无自动播放，减少不必要状态。
联动协议只用两个hidden binding：annualIncome字符串初始65700，resetSerial字符串初始0。工资块仅在用户改变工资输入时emit annualIncome，onState只在resetSerial改变时恢复三个工资输入，忽略初次重复值。现金流块缓存lastAnnualIncome；仅annualIncome发生变化才使用工时模式并覆盖收入框，其他state消息不要覆盖手动收入；收入框直接修改标记手动模式。现金流全局复位自己参数并emit递增resetSerial；工资收到重置恢复并emit65700。初始值不循环emit，所有emit值是字符串。
显示值和计算值一致，onchange时把超过范围值规范化写回，input空值显示待输入不改变上一结果。n整数1..60、收入支出0..1000000、r0..30%、g-10..10%。保持跨块手动和复位正确。14px以上，移动端金额放不下时单列、不逐位断行。所有按钮type=button，原生键盘可用，SVG仅显示不会遮挡点击层，按钮支持选择年。
请在功能准确的前提下做出有气质的“工资条→时间流”视觉。不要加入新的估值论断或把现值等同人的价值。design及scene紧凑；scene动作只有focus/reveal/restore等允许值，演示放demo字段。完整JSON。`};
const runId=crypto.randomUUID(),start=Date.now();await writeFile(dir+'/request.json',JSON.stringify({input,runId,startedAt:new Date().toISOString()},null,2));let call=0;
try{const result=await generateArtifact(input,{...env,MAX_OUTPUT_TOKENS:'20000'},{runId,signal:AbortSignal.timeout(300000),onOutput:async(text,usage)=>{await writeFile(dir+'/model-'+(++call)+'.json',JSON.stringify({text,usage,runId,createdAt:new Date().toISOString()}))},onStatus:e=>console.log(e.type==='status'?e.message:e.type)});await writeFile(dir+'/candidate.json',JSON.stringify({source:input.source,artifact:result.artifact},null,2));console.log('DCF v7 ready')}catch(e){await writeFile(dir+'/failure.json',JSON.stringify({error:String(e),calls:call,runId,elapsedMs:Date.now()-start}));console.log(String(e))}
