// Real source/model/browser calls against the complete local HTTP entry point.
// Storage uses SQLite and the test R2 adapter; production storage is verified separately.
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import app from '../server/app';
import {cloudFixture} from '../tests/cloud-fixture';
const f=cloudFixture(),token=crypto.randomUUID(),dir='artifacts/local-production/'+new Date().toISOString().replace(/[:.]/g,'-');await mkdir(dir,{recursive:true});
const server=createServer(async(req,res)=>{try{const data:Buffer[]=[];for await(const b of req)data.push(b);const request=new Request('http://127.0.0.1:5198'+req.url,{method:req.method,headers:req.headers as Record<string,string>,...(req.method==='GET'||req.method==='HEAD'?{}:{body:Buffer.concat(data)})});const response=await app.fetch(request,{DB:f.DB,MEDIA:f.MEDIA,RUNNER_TOKEN:token});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))}catch(e){res.writeHead(500);res.end(String(e))}});await new Promise<void>(r=>server.listen(5198,'127.0.0.1',r));
const run=()=>new Promise<number>(resolve=>{const child=spawn(process.execPath,['node_modules/tsx/dist/cli.mjs','scripts/release-worker.ts'],{env:{...process.env,RELEASE_URL:'http://127.0.0.1:5198',RUNNER_TOKEN:token,CONTENT_KIND:'knowledge',WORK_ID:'1251918148732559360'},stdio:'inherit'});child.on('exit',c=>resolve(c||0))});
try{const first=await run();await writeFile(dir+'/first-jobs.json',JSON.stringify(f.sqlite.prepare('SELECT * FROM jobs').all(),null,2));if(first)throw Error('本地完整生产遇到系统故障');const published=f.sqlite.prepare("SELECT count(*) AS n FROM jobs WHERE status='published'").get() as any;if(published.n!==1)throw Error('本地未取得合格发布版本，工作流继续暂停');const before=f.sqlite.prepare('SELECT id,repairs,status FROM jobs').all();const second=await run();const after=f.sqlite.prepare('SELECT id,repairs,status FROM jobs').all();if(second||JSON.stringify(before)!==JSON.stringify(after))throw Error('本地去重没有保持任务与修复次数');await writeFile(dir+'/result.json',JSON.stringify({first,second,storage:'local SQLite + R2 adapter',source:'real official API',model:'real DeepSeek API',browser:'real Chromium 740/360',published:1,dedupUnchanged:true},null,2));console.log('本地完整入口发布与重复触发通过：'+dir)}finally{for(const [key,value]of f.objects){const path=dir+'/objects/'+key;await mkdir(path.slice(0,path.lastIndexOf('/')),{recursive:true});await writeFile(path,value)}await writeFile(dir+'/jobs.json',JSON.stringify(f.sqlite.prepare('SELECT * FROM jobs').all(),null,2));server.close();f.sqlite.close()}
